databases:
  - name: lauren-postgres
    databaseName: lauren_postgres
    user: lauren_postgres_user
    plan: free

services:
  - type: web
    name: analytics
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lauren_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
